first_name=input("Please student first name here: ")
last_name=input("Please student last name here: ")
math=int(input("Please student Math grade here: "))
english=int(input("Please student English grade here: "))
print("First name:",first_name)
print("Last name:",last_name)
print("Math grade:",math)
print("English grade:",english)
print("Average grade:",(math+english)/2)
